## Duplicated features

* Both features are identical 
* Sometimes added after OHE 
* Remove duplicates

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")
data = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/FeatureSelection/train_santander.csv', nrows = 5000)
y = data.TARGET
X = data.drop(columns=['TARGET'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

X_train.shape, X_test.shape

Mounted at /content/gdrive

((4000, 370), (1000, 370))

## Removing duplicate features

In [ ]:
[col for col in data.columns if data[col].isnull().sum() > 0]

[]

### Duplicates using Pandas

* Transpose 
* Find 
* Remove

In [ ]:
X_train.head()

        ID  var3  ...  saldo_medio_var44_ult3          var38
1558  3082     5  ...                     0.0   68397.030000
672   1341     2  ...                     0.0  117310.979016
4592  9186     2  ...                     0.0  123680.700000
4620  9246     2  ...                     0.0  117310.979016
2840  5683     2  ...                     0.0   58046.130000

[5 rows x 370 columns]

In [ ]:
X_train = X_train.T
X_train.head()

                            1558    672     4592  ...    3114    4241    3817
ID                       3082.00  1341.0  9186.0  ...  6272.0  8513.0  7658.0
var3                        5.00     2.0     2.0  ...     2.0     2.0     2.0
var15                      52.00    24.0    27.0  ...    27.0    24.0    23.0
imp_ent_var16_ult1        450.00     0.0     0.0  ...     0.0     0.0     0.0
imp_op_var39_comer_ult1   270.69     0.0     0.0  ...     0.0     0.0     0.0

[5 rows x 4000 columns]

In [ ]:
X_train.duplicated().sum()

125

In [ ]:
X_train[X_train.duplicated()]

                              1558  672   4592  4620  ...  1528  3114  4241  3817
ind_var2                       0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
ind_var6                       0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
ind_var13_largo                0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
ind_var13_medio_0              0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
ind_var13_medio                0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
...                            ...   ...   ...   ...  ...   ...   ...   ...   ...
saldo_medio_var13_medio_ult3   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
saldo_medio_var17_hace3        0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
saldo_medio_var29_hace2        0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
saldo_medio_var29_hace3        0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0
saldo_medio_var29_ult3         0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0

[125 rows x 4000 columns]

In [ ]:
duplicates = X_train[X_train.duplicated()].index.values
duplicates

array(['ind_var2', 'ind_var6', 'ind_var13_largo', 'ind_var13_medio_0',
       'ind_var13_medio', 'ind_var18_0', 'ind_var18', 'ind_var26',
       'ind_var25', 'ind_var27_0', 'ind_var28_0', 'ind_var28',
       'ind_var27', 'ind_var29_0', 'ind_var29', 'ind_var32_0',
       'ind_var32', 'ind_var33', 'ind_var34_0', 'ind_var34', 'ind_var37',
       'ind_var40_0', 'ind_var40', 'ind_var41', 'ind_var39', 'ind_var44',
       'ind_var46_0', 'ind_var46', 'num_var6', 'num_var13_medio_0',
       'num_var13_medio', 'num_var18_0', 'num_var18', 'num_var26',
       'num_var25', 'num_var27_0', 'num_var28_0', 'num_var28',
       'num_var27', 'num_var29_0', 'num_var29', 'num_var32', 'num_var33',
       'num_var34_0', 'num_var34', 'num_var37', 'num_var40_0',
       'num_var40', 'num_var41', 'num_var39', 'num_var44', 'num_var46_0',
       'num_var46', 'saldo_var13_medio', 'saldo_var18', 'saldo_var28',
       'saldo_var27', 'saldo_var29', 'saldo_var34', 'saldo_var40',
       'saldo_var41', 'saldo_var46', 'delta_imp_amort_var18_1y3',
       'delta_imp_amort_var34_1y3', 'delta_imp_reemb_var17_1y3',
       'delta_imp_reemb_var33_1y3', 'delta_imp_trasp_var17_out_1y3',
       'delta_imp_trasp_var33_in_1y3', 'delta_imp_trasp_var33_out_1y3',
       'delta_num_aport_var13_1y3', 'delta_num_aport_var17_1y3',
       'delta_num_reemb_var13_1y3', 'delta_num_reemb_var17_1y3',
       'delta_num_reemb_var33_1y3', 'delta_num_trasp_var17_in_1y3',
       'delta_num_trasp_var17_out_1y3', 'delta_num_trasp_var33_in_1y3',
       'delta_num_trasp_var33_out_1y3', 'delta_num_venta_var44_1y3',
       'imp_amort_var18_hace3', 'imp_amort_var18_ult1',
       'imp_amort_var34_hace3', 'imp_amort_var34_ult1',
       'imp_var7_emit_ult1', 'imp_reemb_var13_hace3',
       'imp_reemb_var17_hace3', 'imp_reemb_var17_ult1',
       'imp_reemb_var33_hace3', 'imp_reemb_var33_ult1',
       'imp_trasp_var17_in_hace3', 'imp_trasp_var17_out_hace3',
       'imp_trasp_var17_out_ult1', 'imp_trasp_var33_in_hace3',
       'imp_trasp_var33_in_ult1', 'imp_trasp_var33_out_hace3',
       'imp_trasp_var33_out_ult1', 'imp_venta_var44_hace3',
       'ind_var7_emit_ult1', 'num_var2_0_ult1', 'num_var2_ult1',
       'num_var7_emit_ult1', 'num_meses_var13_medio_ult3',
       'num_meses_var29_ult3', 'num_reemb_var13_hace3',
       'num_reemb_var17_hace3', 'num_reemb_var17_ult1',
       'num_reemb_var33_hace3', 'num_reemb_var33_ult1',
       'num_trasp_var17_in_hace3', 'num_trasp_var17_out_hace3',
       'num_trasp_var17_out_ult1', 'num_trasp_var33_in_hace3',
       'num_trasp_var33_in_ult1', 'num_trasp_var33_out_hace3',
       'num_trasp_var33_out_ult1', 'num_venta_var44_hace3',
       'saldo_var2_ult1', 'saldo_medio_var13_medio_hace2',
       'saldo_medio_var13_medio_hace3', 'saldo_medio_var13_medio_ult1',
       'saldo_medio_var13_medio_ult3', 'saldo_medio_var17_hace3',
       'saldo_medio_var29_hace2', 'saldo_medio_var29_hace3',
       'saldo_medio_var29_ult3'], dtype=object)

In [ ]:
X_train = X_train.drop_duplicates(keep='first').T
X_train.shape

(4000, 245)