## Frequency Encoding

- For high cardinality 

- Replace each label by its frequency of occurence in the dataset

- Highly used in Kaggle competitions 

### Pros

- Easy
- Does not expand the feature space

### Disadvantages

- Variables having the same frequency will be lost

In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [25]:
from google.colab import drive
drive.mount('/content/gdrive')
data = pd.read_csv("gdrive/My Drive/Colab Notebooks/FeatureEngineering/trainh.csv")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [26]:
data.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [27]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [29]:
# Get variables with more than n categories 
n = 10
cats = []
for col in data.columns:
    if data[col].dtypes =='O': 
        if len(data[col].unique())>n: 
            print('{} categories : {} '.format(col, len(data[col].unique())))
            cats.append(col)

Neighborhood categories : 25
Exterior1st categories : 15
Exterior2nd categories : 16

In [30]:
for col in cats:
    if data[col].dtypes =='O': # if the variable is categorical
      print(100*data.groupby(col)[col].count()/np.float(len(data)))
      print()

Neighborhood
Blmngtn     1.164384
Blueste     0.136986
BrDale      1.095890
BrkSide     3.972603
ClearCr     1.917808
CollgCr    10.273973
Crawfor     3.493151
Edwards     6.849315
Gilbert     5.410959
IDOTRR      2.534247
MeadowV     1.164384
Mitchel     3.356164
NAmes      15.410959
NPkVill     0.616438
NWAmes      5.000000
NoRidge     2.808219
NridgHt     5.273973
OldTown     7.739726
SWISU       1.712329
Sawyer      5.068493
SawyerW     4.041096
Somerst     5.890411
StoneBr     1.712329
Timber      2.602740
Veenker     0.753425
Name: Neighborhood, dtype: float64

Exterior1st
AsbShng     1.369863
AsphShn     0.068493
BrkComm     0.136986
BrkFace     3.424658
CBlock      0.068493
CemntBd     4.178082
HdBoard    15.205479
ImStucc     0.068493
MetalSd    15.068493
Plywood     7.397260
Stone       0.136986
Stucco      1.712329
VinylSd    35.273973
Wd Sdng    14.109589
WdShing     1.780822
Name: Exterior1st, dtype: float64

Exterior2nd
AsbShng     1.369863
AsphShn     0.205479
Brk Cmn     0.479452
BrkFace     1.712329
CBlock      0.068493
CmentBd     4.109589
HdBoard    14.178082
ImStucc     0.684932
MetalSd    14.657534
Other       0.068493
Plywood     9.726027
Stone       0.342466
Stucco      1.780822
VinylSd    34.520548
Wd Sdng    13.493151
Wd Shng     2.602740
Name: Exterior2nd, dtype: float64

In [31]:
for col in cats:
    if data[col].dtypes =='O': # if the variable is categorical
      print(data.groupby(col)[col].count())
      print()

Neighborhood
Blmngtn     17
Blueste      2
BrDale      16
BrkSide     58
ClearCr     28
CollgCr    150
Crawfor     51
Edwards    100
Gilbert     79
IDOTRR      37
MeadowV     17
Mitchel     49
NAmes      225
NPkVill      9
NWAmes      73
NoRidge     41
NridgHt     77
OldTown    113
SWISU       25
Sawyer      74
SawyerW     59
Somerst     86
StoneBr     25
Timber      38
Veenker     11
Name: Neighborhood, dtype: int64

Exterior1st
AsbShng     20
AsphShn      1
BrkComm      2
BrkFace     50
CBlock       1
CemntBd     61
HdBoard    222
ImStucc      1
MetalSd    220
Plywood    108
Stone        2
Stucco      25
VinylSd    515
Wd Sdng    206
WdShing     26
Name: Exterior1st, dtype: int64

Exterior2nd
AsbShng     20
AsphShn      3
Brk Cmn      7
BrkFace     25
CBlock       1
CmentBd     60
HdBoard    207
ImStucc     10
MetalSd    214
Other        1
Plywood    142
Stone        5
Stucco      26
VinylSd    504
Wd Sdng    197
Wd Shng     38
Name: Exterior2nd, dtype: int64

In [34]:
data[cats].isnull().sum()

Neighborhood    0
Exterior1st     0
Exterior2nd     0
dtype: int64

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[cats], data.SalePrice,
                                                    test_size=0.2)
X_train.shape, X_test.shape

((1168, 3), (292, 3))

In [36]:
def frequency_encoding(X_train, X_test, cols):
  import random
  for col in cols:
    mapper = X_train[col].value_counts().to_dict()
    X_train[col] = X_train[col].map(mapper)
    X_test[col] = X_test[col].map(mapper)
    #X_test[col] = X_test[col].fillna(random.choice(list(mapper.values())))

In [37]:
X_train.head()

    Neighborhood Exterior1st Exterior2nd
435      CollgCr     VinylSd     VinylSd
953      Mitchel     HdBoard     HdBoard
18       SawyerW     VinylSd     VinylSd
366        NAmes     Plywood     Plywood
25       NridgHt     VinylSd     VinylSd

In [38]:
frequency_encoding(X_train, X_test, cats)

In [39]:
X_train.head()

     Neighborhood  Exterior1st  Exterior2nd
435           118          409          398
953            37          186          172
18             48          409          398
366           178           84          113
25             65          409          398